version: '3'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - bc_network
    environment:
      - TZ=UTC
    ports:
      - '8081:8080'
  postgres:
    restart: always
    image: 'postgres:latest'
    networks:
      - bc_network
    environment:
      - 'POSTGRES_DB=bc'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'

volumes:
  postgres-db:
    driver: local

networks:
  bc_network:
      external: true
